apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nw-products
  template:
    metadata:
      labels:
        app: nw-products
    spec:
      containers:
        - name: nw-products
          image: learnwithvinod/nw-products
          ports:
            - containerPort: 8080
          env:
            - name: CATEGORY_SERVICE_HOST
              value: nw-categories-service
            - name: CATEGORY_SERVICE_PORT
              value: '8080'
            - name: SUPPLIER_SERVICE_HOST
              value: nw-suppliers-service
            - name: SUPPLIER_SERVICE_PORT
              value: '8080'
            
---
apiVersion: v1
kind: Service
metadata:
  name: nw-products-service
spec:
  selector:
    app: nw-products
  ports:
    - protocol: TCP
      port: 8080 # Service port (internal to cluster)
      targetPort: 8080 # Pod's port (container)
      nodePort: 30000
  type: NodePort